// ============================================================================
// dd_eft_test_device.cpp — the DEVICE half of T1.1's EFT unit tests for DD.
// ============================================================================
// Added by CORE_PLAN section C4 step 2 (chunk C), which splits the eight MIXED
// translation units — the ones carrying a host binary128 oracle in the same file
// as a kernel launch — into a host half and a device half.
//
// WHY THE SPLIT HAS TO HAPPEN AT ALL
//   nvcc gives EVERY translation unit a device pass, and it rejects the 128-bit
//   float inside STL member signatures: std::vector<__float128> does not compile
//   under nvcc no matter what flags are passed (S6). So a TU that both scores
//   against the binary128 oracle AND launches a kernel cannot be built for a GPU.
//   dd_eft_test.cpp was exactly that: Tests A/B/C score against binary128, Test D
//   launched. A/B/C stay in dd_eft_test.cpp; Test D is this file.
//
//   This TU therefore contains NO 128-bit type and no MPFR, and that is not a
//   convention — scripts/check_device_tu_purity.sh preprocesses it and fails if
//   any in-repo file puts the type into it.
//
// WHAT REPLACES THE ORACLE, AND WHY IT IS NOT A WEAKER TEST BY FIAT
//   The host half proves exactness the strong way: widen to binary128, where the
//   54-bit sum and 106-bit product are both exact, and demand bit equality. That
//   argument needs a type wider than a double and so cannot cross onto a GPU.
//
//   What CAN cross is a second exact transform. Both EFTs under test have an
//   independent, provably-exact alternative that needs nothing wider than an
//   FP64 register:
//
//     twoSum   <-> Dekker's fast2sum on MAGNITUDE-SORTED operands.
//                  With |x| >= |y| and x+y finite,
//                      s = x + y ;  e = y - (s - x)
//                  is exact (Dekker 1971; Muller et al., "Handbook of Floating-
//                  Point Arithmetic", Thm 4.3). It is 3 flops against Knuth's 6
//                  and a structurally different expression, so the two agreeing
//                  bit-for-bit is real evidence, not a tautology.
//
//     twoProd  <-> the FMA identity.  p = a*b ; e = fma(a, b, -p).
//                  IEEE 754-2019 requires fma to round a*b + c ONCE from the
//                  exact value. a*b - p is exactly representable in a double
//                  whenever the product neither overflows nor underflows, so the
//                  single rounding is the identity and e is exact. This is the
//                  textbook FMA-based twoProduct, which is a genuinely different
//                  algorithm from Veltkamp/Dekker splitting — no splitter
//                  constant, no cross terms.
//
//   HONEST LIMITATION, stated rather than buried: this is a cross-check between
//   two independent exact transforms, not a widening oracle. It would miss a
//   defect that broke Knuth twoSum and Dekker fast2sum in precisely the same way
//   (or Dekker twoProduct and the hardware FMA in precisely the same way). The
//   host half, which keeps the binary128 oracle over a much larger corpus, is
//   what rules that out; this half is what carries the claim onto hardware the
//   oracle cannot reach.
//
//   THIS IS NOT A SECOND SCORER. docs/CORRECTNESS.md permits one measurement and
//   one verdict per point, and both refer to the ULP measurement in
//   validation/sweep/. Nothing here computes a ulp, a digit count, or a
//   tolerance: every comparison below is `==` on a pair of doubles.
//
// WHY THE INPUTS ARE GENERATED BY EXPONENT BAND
//   dd_eft_test.cpp's prod_in_domain() decides "is this pair inside Dekker's
//   proven domain" by forming the EXACT product in binary128 and bounding its
//   magnitude. That predicate cannot come here. Two things replace it:
//
//     1. The random corpus is generated so that it is in-domain BY CONSTRUCTION:
//        |x| in [2^-400, 2^401), which puts |a*b| in [2^-800, 2^802), inside the
//        2^-969 underflow headroom and far below DBL_MAX. Nothing is skipped and
//        nothing has to be tested for.
//     2. The corner-case corpus, which is deliberately full of the magnitudes
//        rule 1 excludes, is filtered by an EXPONENT-ONLY predicate built on
//        frexp. It is conservative — it can refuse a pair the binary128 test
//        would have admitted — and it never admits one that test would refuse,
//        which is the direction that matters.
//
//   And the generator is not trusted on its say-so: main() re-checks every
//   generated pair against that predicate and fails if one is out of domain. A
//   test whose inputs were silently all skipped is a test that proved nothing.
//
// CONTRACTION POSTURE IS UNCHANGED. This target is registered through
// xpm_add_device_eft_test(), so it is built -ffp-contract=off / --fmad=false for
// the same reason the host half is: `a1*b1 - p` must stay two rounded
// operations. The fma() in the reference is an EXPLICIT correctly-rounded fused
// operation and is unaffected by that flag in either direction — which is
// precisely why it is usable as a contraction-immune reference.
// ============================================================================

#include "device_harness.hpp"
#include "test_utils_device.hpp"
#include "corpus.hpp"
#include <xp/dd_math.hpp>

#include <cmath>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <limits>
#include <random>
#include <utility>
#include <vector>

using namespace kokkos_ep;

// ----------------------------------------------------------------------------
// Scalar fma, host+device. include/xp/config.hpp's detail:: dispatch covers the
// functions the LIBRARY calls and fma is not one of them; rather than widen a
// shipped header for a test's benefit, this mirrors the same two-branch pattern
// locally. ::fma is the vendor's __device__ overload under CUDA/HIP; std::fma is
// the only spelling the standard guarantees on the host.
// ----------------------------------------------------------------------------
XPMATH_INLINE_FUNCTION double dev_fma(double a, double b, double c) {
#if defined(XPMATH_ON_DEVICE_CUDA_OR_HIP)
    return ::fma(a, b, c);
#else
    return std::fma(a, b, c);
#endif
}

// ----------------------------------------------------------------------------
// The two EFT primitives under test. COPIED VERBATIM from dd_eft_test.cpp, which
// in turn mirrors the sequences embedded in dd_math.hpp's add / multiply for raw
// doubles (lo == 0). The duplication is the same deliberate mirror-and-comment
// the host half documents; if these ever drift from that copy, that is itself a
// defect worth catching.
// ----------------------------------------------------------------------------

struct TwoOut { double hi; double lo; };

XPMATH_INLINE_FUNCTION TwoOut two_sum(double a, double b) {
    double s   = a + b;
    double e   = s - a;
    double err = (b - e) + (a - (s - e));
    return TwoOut{ s, err };
}

XPMATH_INLINE_FUNCTION TwoOut two_prod_dekker(double a, double b) {
    const double split = 134217729.0;        // 2^27 + 1
    double cona = a * split, conb = b * split;
    double a1 = cona - (cona - a), b1 = conb - (conb - b);
    double a2 = a - a1,            b2 = b - b1;
    double p  = a * b;                                             // fl(a*b)
    double e  = (((a1 * b1 - p) + a1 * b2) + a2 * b1) + a2 * b2;   // exact error
    return TwoOut{ p, e };
}

// ----------------------------------------------------------------------------
// The two independent exact references. See the header block for the proofs.
// ----------------------------------------------------------------------------

// Dekker fast2sum, with the magnitude sort done here so callers cannot forget
// it. The sort is a comparison and a swap, neither of which rounds, so the
// precondition |x| >= |y| is met by construction rather than by assumption.
XPMATH_INLINE_FUNCTION TwoOut ref_fast2sum(double a, double b) {
    double x = a, y = b;
    if (xp::detail::fabs(y) > xp::detail::fabs(x)) { double t = x; x = y; y = t; }
    double s = x + y;
    double e = y - (s - x);
    return TwoOut{ s, e };
}

// FMA-based twoProduct.
XPMATH_INLINE_FUNCTION TwoOut ref_fma_two_prod(double a, double b) {
    double p = a * b;
    double e = dev_fma(a, b, -p);
    return TwoOut{ p, e };
}

// ----------------------------------------------------------------------------
// Host-side domain predicates. Both are expressed WITHOUT a type wider than a
// double; see the header block on why and on which direction the conservatism
// runs.
// ----------------------------------------------------------------------------

// twoSum / fast2sum domain: finite operands whose sum does not overflow. Same
// predicate the host half uses, and it never needed the oracle.
static bool sum_in_domain(double a, double b) {
    if (!std::isfinite(a) || !std::isfinite(b)) return false;
    return std::isfinite(a + b);
}

// 2^996: |x| below this keeps x*(2^27+1) finite, so the Veltkamp split does not
// overflow to inf and then to inf-inf = NaN.
static double split_safe_max() { return std::ldexp(1.0, 996); }

// Dekker twoProduct domain, by EXPONENT rather than by exact magnitude.
// frexp(x, &e) writes x = m * 2^e with |m| in [0.5, 1), so |x| lies in
// [2^(e-1), 2^e) and therefore |a*b| lies in [2^(ea+eb-2), 2^(ea+eb)).
// Requiring the lower end at or above 2^-969 (the host half's underflow
// headroom: the error term sits ~one ulp below the product, so a product at
// 2^-969 keeps the error term normal) and the upper end below 2^1024 is a
// CONSERVATIVE reading of the same bound the binary128 predicate applies to the
// exact value. It can refuse a pair binary128 would accept; it cannot accept one
// binary128 would refuse, which is the only direction that could turn a real
// defect into a pass.
static bool prod_in_domain(double a, double b) {
    if (!std::isfinite(a) || !std::isfinite(b)) return false;
    const double dmin = std::numeric_limits<double>::min();   // smallest normal
    auto normal_or_zero = [dmin](double x) {
        return x == 0.0 || std::fabs(x) >= dmin;              // reject subnormals
    };
    if (!normal_or_zero(a) || !normal_or_zero(b)) return false;
    // Splitter overflow gates the zero shortcut too: even x*0 splits x first.
    const double ssm = split_safe_max();
    if (std::fabs(a) >= ssm || std::fabs(b) >= ssm) return false;
    if (a == 0.0 || b == 0.0) return true;                    // exact product 0
    int ea = 0, eb = 0;
    std::frexp(a, &ea);
    std::frexp(b, &eb);
    if (ea + eb - 2 < -969) return false;   // error term could fall subnormal
    if (ea + eb > 1023)     return false;   // product could overflow
    return true;
}

// ----------------------------------------------------------------------------
// Input generation. Mantissa uniform in [1,2), exponent uniform in [-400, 400],
// random sign: |x| in [2^-400, 2^401), which makes every PAIR in-domain for both
// transforms by construction (see header). Deliberately not the host half's
// uniform_real_distribution over [-1e100, 1e100]: that one is in-domain in
// practice but only because the distribution essentially never emits a small
// magnitude, which is an argument about a random number generator rather than
// about the transform.
// ----------------------------------------------------------------------------
static double gen_banded(std::mt19937_64& g) {
    std::uniform_real_distribution<double> dm(1.0, 2.0);
    std::uniform_int_distribution<int>     de(-400, 400);
    double v = std::ldexp(dm(g), de(g));
    return (g() & 1u) ? v : -v;
}

// ----------------------------------------------------------------------------
// Diagnostics.
// ----------------------------------------------------------------------------
static void print_mismatch(const char* which, double a, double b,
                           TwoOut got, TwoOut ref) {
    uint64_t ab, bb;
    std::memcpy(&ab, &a, sizeof(double));
    std::memcpy(&bb, &b, sizeof(double));
    std::printf("    MISMATCH %s  a=%.17g (0x%016llx)  b=%.17g (0x%016llx)\n"
                "        device hi=%.17g lo=%.17g   reference hi=%.17g lo=%.17g\n",
                which, a, (unsigned long long)ab, b, (unsigned long long)bb,
                got.hi, got.lo, ref.hi, ref.lo);
}

// ----------------------------------------------------------------------------
// The kernel. A trivially-copyable struct holding raw device pointers, NOT a
// lambda: tests/device_harness.hpp passes F by value into a __global__ and
// deliberately does not require nvcc --extended-lambda of its callers.
//
// All FOUR transforms run ON THE DEVICE. Computing the references host-side and
// shipping them in would test the host's arithmetic against the device's, which
// is a different and weaker question — a GPU that got BOTH transforms wrong in
// the same way would still be caught here, because the two transforms are
// independent, whereas a host/device comparison would only catch a GPU that
// disagreed with an x86 CPU.
// ----------------------------------------------------------------------------
struct EftKernel {
    const double* a;
    const double* b;
    double* s_hi;  double* s_lo;    // Knuth twoSum
    double* p_hi;  double* p_lo;    // Dekker twoProduct
    double* rs_hi; double* rs_lo;   // fast2sum reference
    double* rp_hi; double* rp_lo;   // FMA reference

    XPMATH_INLINE_FUNCTION void operator()(std::size_t i) const {
        TwoOut s  = two_sum(a[i], b[i]);
        TwoOut p  = two_prod_dekker(a[i], b[i]);
        TwoOut rs = ref_fast2sum(a[i], b[i]);
        TwoOut rp = ref_fma_two_prod(a[i], b[i]);
        s_hi[i]  = s.hi;  s_lo[i]  = s.lo;
        p_hi[i]  = p.hi;  p_lo[i]  = p.lo;
        rs_hi[i] = rs.hi; rs_lo[i] = rs.lo;
        rp_hi[i] = rp.hi; rp_lo[i] = rp.lo;
    }
};

struct DeviceResult { long sum_tested = 0, sum_fail = 0, prod_tested = 0, prod_fail = 0; };

// Run one batch of pairs through the harness and compare on the host. Every
// pair is LAUNCHED; the domain predicates decide only which of the two
// comparisons it is eligible for, so a pair out of Dekker's domain still counts
// toward twoSum.
static DeviceResult run_batch(const char* label,
                              const std::vector<std::pair<double,double>>& in,
                              int& samples_left) {
    DeviceResult R;
    const std::size_t n = in.size();
    if (n == 0) {
        std::printf("    [%s] EMPTY BATCH — nothing was launched\n", label);
        return R;
    }

    xpt::buffer<double> va(n), vb(n);
    xpt::buffer<double> s_hi(n), s_lo(n), p_hi(n), p_lo(n);
    xpt::buffer<double> rs_hi(n), rs_lo(n), rp_hi(n), rp_lo(n);
    for (std::size_t i = 0; i < n; ++i) {
        va.host()[i] = in[i].first;
        vb.host()[i] = in[i].second;
    }
    va.to_device();
    vb.to_device();

    xpt::parallel_for_n(n, EftKernel{va.device(), vb.device(),
                                     s_hi.device(), s_lo.device(),
                                     p_hi.device(), p_lo.device(),
                                     rs_hi.device(), rs_lo.device(),
                                     rp_hi.device(), rp_lo.device()});

    s_hi.from_device();  s_lo.from_device();
    p_hi.from_device();  p_lo.from_device();
    rs_hi.from_device(); rs_lo.from_device();
    rp_hi.from_device(); rp_lo.from_device();

    for (std::size_t i = 0; i < n; ++i) {
        const double a = in[i].first, b = in[i].second;
        if (sum_in_domain(a, b)) {
            ++R.sum_tested;
            TwoOut got{ s_hi.host()[i],  s_lo.host()[i]  };
            TwoOut ref{ rs_hi.host()[i], rs_lo.host()[i] };
            if (got.hi != ref.hi || got.lo != ref.lo) {
                ++R.sum_fail;
                if (samples_left > 0) { print_mismatch("twoSum", a, b, got, ref); --samples_left; }
            }
        }
        if (prod_in_domain(a, b)) {
            ++R.prod_tested;
            TwoOut got{ p_hi.host()[i],  p_lo.host()[i]  };
            TwoOut ref{ rp_hi.host()[i], rp_lo.host()[i] };
            if (got.hi != ref.hi || got.lo != ref.lo) {
                ++R.prod_fail;
                if (samples_left > 0) { print_mismatch("twoProd", a, b, got, ref); --samples_left; }
            }
        }
    }

    std::printf("    [%s] n=%zu  twoSum: tested=%ld failures=%ld   "
                "twoProd: tested=%ld failures=%ld\n",
                label, n, R.sum_tested, R.sum_fail, R.prod_tested, R.prod_fail);
    return R;
}

// ============================================================================
int main(int, char**) {
    int rc = 0;

    std::printf("=== dd_eft_test_device (T1.1, C4 device half): DD twoSum + Dekker "
                "twoProd on the device ===\n");
    std::printf("backend: %s\n", xpt::where_name());
    std::printf("reference: Dekker fast2sum (sorted) for twoSum, fma(a,b,-a*b) for "
                "twoProd — both exact, neither needs a wider type\n\n");

    // -- Batch 1: 200k exponent-banded random pairs, in-domain by construction --
    std::printf("[Batch 1] 2x10^5 random pairs, |x| in [2^-400, 2^401)\n");
    std::vector<std::pair<double,double>> banded;
    {
        const int nd = 200'000;
        banded.reserve(nd);
        std::mt19937_64 g(99999ULL);
        for (int i = 0; i < nd; ++i) {
            double a = gen_banded(g), b = gen_banded(g);
            banded.emplace_back(a, b);
        }
    }
    // THE GENERATOR IS CHECKED, NOT TRUSTED. If the band were wrong, every pair
    // would silently fall out of domain, both tested counts would be 0, and the
    // batch would "pass" having measured nothing.
    {
        long bad = 0;
        for (const auto& pr : banded)
            if (!sum_in_domain(pr.first, pr.second) || !prod_in_domain(pr.first, pr.second)) ++bad;
        std::printf("    generator self-check: %ld of %zu pairs out of domain (want 0)\n",
                    bad, banded.size());
        KOKKOS_EP_ASSERT(bad == 0,
                         "the exponent-banded generator produced an out-of-domain pair — "
                         "the batch would have measured less than it claims");
    }

    int samples_left = 5;
    DeviceResult B1 = run_batch("banded", banded, samples_left);

    // -- Batch 2: the corner-case corpus, cross-product --------------------
    // Subnormals, +/-0, powers of two, DBL_MAX-adjacent values: exactly the
    // magnitudes batch 1 excludes by construction. Most are out of Dekker's
    // domain and are skipped there while still exercising twoSum, which has no
    // underflow hazard and is defined on subnormals.
    std::printf("[Batch 2] corner-case corpus cross-product (T0.2 corpus, i<j)\n");
    std::vector<std::pair<double,double>> corner;
    {
        corpus::CorpusFlags flags;   // inf/zero/subnormals on, nan off
        std::vector<double> xs = corpus::unary<double>(flags);
        for (std::size_t i = 0; i < xs.size(); ++i)
            for (std::size_t j = i + 1; j < xs.size(); ++j)
                corner.emplace_back(xs[i], xs[j]);
    }
    DeviceResult B2 = run_batch("corpus", corner, samples_left);

    // -- Gates -------------------------------------------------------------
    const long sum_tested  = B1.sum_tested  + B2.sum_tested;
    const long sum_fail    = B1.sum_fail    + B2.sum_fail;
    const long prod_tested = B1.prod_tested + B2.prod_tested;
    const long prod_fail   = B1.prod_fail   + B2.prod_fail;

    std::printf("\ntotals: twoSum tested=%ld failures=%ld   twoProd tested=%ld failures=%ld\n",
                sum_tested, sum_fail, prod_tested, prod_fail);

    // A zero tested count is a vacuous pass, so it is a failure.
    KOKKOS_EP_ASSERT(sum_tested  > 0, "no twoSum pair was in domain — nothing was tested");
    KOKKOS_EP_ASSERT(prod_tested > 0, "no twoProd pair was in domain — nothing was tested");
    KOKKOS_EP_ASSERT(sum_fail  == 0,
                     "device Knuth twoSum disagreed with Dekker fast2sum on an in-domain pair");
    KOKKOS_EP_ASSERT(prod_fail == 0,
                     "device Dekker twoProduct disagreed with the FMA twoProduct on an "
                     "in-domain pair");
    // A nonzero vendor code is a TEST FAILURE, not a warning: a launch that never
    // ran leaves the output buffers at whatever the allocator returned, and the
    // comparison loop cannot tell that from a clean pass. Sticky since process
    // start, so a later good call cannot erase it.
    KOKKOS_EP_ASSERT(xpt::last_error() == 0,
                     "device harness reported a nonzero vendor error code");

    rc = ep_exit_code();
    std::printf("=== dd_eft_test_device: %s ===\n", rc == 0 ? "ALL PASSED" : "FAILURES PRESENT");
    return rc;
}
