// Constant generator for qf_math.hpp (QuadFloat = 4×FP32, ~96-bit significand).
//
// Extends the scripts/gen_ff_constants.cpp pattern (2×FP32 Route-A split) to
// four FP32 words. Each mathematical constant is held to full accuracy in
// __float128 (113-bit significand — ample headroom over QF's ~96 bits), then
// decomposed into four non-overlapping FP32 components by SUCCESSIVE SPLITTING:
//
//   f0 = (float)x                       // round-to-nearest FP32 of x
//   r1 = x - f0                          // exact residual (computed in f128)
//   f1 = (float)r1
//   r2 = r1 - f1
//   f2 = (float)r2
//   r3 = r2 - f2
//   f3 = (float)r3
//
// This is the length-4 analogue of the FF Route-A split and yields a
// Priest-normalized expansion (|f_{i+1}| <= 1/2 ulp(f_i)) by construction,
// because each step peels off exactly the round-to-nearest FP32 of the running
// remainder. Same algorithm QD's qd_const.cpp uses to seed its constants, only
// at FP32 word width instead of FP64.
//
// Build: g++ -std=c++17 -fext-numeric-literals -O2 scripts/gen_qf_constants.cpp \
//            -lquadmath -o scripts/gen_qf_constants
//        (-fext-numeric-literals is required for the __float128 'Q' suffix under
//         -std=c++17; drop it if building with -std=gnu++NN.)
// Run:   ./scripts/gen_qf_constants
// Paste the printed block into third_party/include/qf_math.hpp (constants section).

#include <cstdio>
#include <cstdint>
#include <cstring>
#include <quadmath.h>

struct Const { __float128 value; const char* name; const char* desc; };

static uint32_t float_to_bits(float f) {
    uint32_t b; std::memcpy(&b, &f, sizeof(float)); return b;
}

int main() {
    // High-accuracy source values in __float128 (M_* q suffixed literals are
    // correctly rounded to 113 bits by the compiler / libquadmath).
    const __float128 pi    = M_PIq;
    const __float128 e     = expq(1.0Q);
    const __float128 log2v = logq(2.0Q);
    const __float128 log10v= logq(10.0Q);
    const __float128 sqrt2 = sqrtq(2.0Q);
    // Euler-Mascheroni gamma is not a libquadmath literal; use its known value
    // to 36 digits (correctly rounds into 113 bits, far beyond QF's ~29).
    const __float128 egamma = strtoflt128("0.57721566490153286060651209008240243", nullptr);

    const Const CONSTANTS[] = {
        { pi,     "QuadFloat_pi",          "pi"          },
        { e,      "QuadFloat_e",           "e"           },
        { log2v,  "QuadFloat_log2",        "ln(2)"       },
        { log10v, "QuadFloat_log10",       "ln(10)"      },
        { sqrt2,  "QuadFloat_sqrt2",       "sqrt(2)"     },
        { egamma, "QuadFloat_euler_gamma", "Euler gamma" },
    };

    std::printf("// Auto-generated by scripts/gen_qf_constants.cpp -- do not edit by hand.\n");
    std::printf("// Successive-splitting of a 113-bit __float128 constant into 4 FP32 words.\n\n");
    for (const auto& c : CONSTANTS) {
        __float128 r = c.value;
        float f[4];
        uint32_t bits[4];
        for (int i = 0; i < 4; ++i) {
            f[i]    = (float)r;                 // nearest FP32 of running remainder
            r       = r - (__float128)f[i];     // exact residual in f128
            bits[i] = float_to_bits(f[i]);
        }
        // Report reconstruction error for the record (should be < 2^-96).
        __float128 recon = (__float128)f[0] + (__float128)f[1]
                         + (__float128)f[2] + (__float128)f[3];
        __float128 relerr = c.value != 0 ? fabsq((recon - c.value) / c.value) : 0;
        char errbuf[64];
        quadmath_snprintf(errbuf, sizeof(errbuf), "%.3Qe", relerr);
        std::printf("KOKKOS_INLINE_FUNCTION QuadFloat %-22s() { "
                    "return QuadFloat::from_bits(0x%08xU, 0x%08xU, 0x%08xU, 0x%08xU); } "
                    "// %-11s  rel_err=%s\n",
                    c.name, bits[0], bits[1], bits[2], bits[3], c.desc, errbuf);
    }
    return 0;
}
