#!/usr/bin/env python3
"""Generate DD-precision Lanczos coefficients for dd_math.hpp's tgamma (task B1).

Emits the `DoubleDouble::from_bits(hi, lo)` declarations pasted into
`third_party/include/dd_math.hpp`'s tgamma body.

Requires mpmath.  On this system:  python3.12 scripts/gen_dd_lanczos_coeffs.py

WHY THIS SCRIPT EXISTS
  The published Lanczos coefficient tables (Godfrey g=7, Boost lanczos24m113)
  are either too low-order for DD precision or are given for the *rational*
  (ratio-of-polynomials) evaluation form.  This project's tgamma uses the
  *partial-fraction* form  c_0 + sum_k c_k/(x+k), so the coefficients must be
  derived for that form at the chosen g.  They are recomputed here rather than
  transcribed, so the 2*N magic numbers in dd_math.hpp are reproducible.

METHOD
  For a chosen (g, N), the Lanczos identity is exact at the N interpolation
  nodes z = 0..N-1 when the coefficients solve the Cauchy-like linear system

      c_0 + sum_{k=1}^{N-1} c_k/(z+k) = F_g(z),
      F_g(z) = Gamma(z+1) / ( sqrt(2*pi) * (z+g+1/2)^(z+1/2) * e^{-(z+g+1/2)} ).

  Solved at 150-decimal-digit precision (the system is ill-conditioned; the
  working precision is far above the ~32 digits retained).  Each coefficient is
  then split into a DD pair via  hi = double(c),  lo = double(c - hi),  both
  roundings performed at full mpmath precision.

CHOICE OF (g, N) -- see the B1 block in docs/TEST_SUITE_PLAN.md
  Two error sources move in opposite directions as g grows:
    * Lanczos truncation error DECREASES with g;
    * the partial-fraction coefficients GROW (max|c_k| ~ 10^(g/2)), and since
      the sum itself is O(1) their cancellation DESTROYS precision at a rate of
      log10(max|c_k|) digits.
  The rational form Boost uses is immune to the second effect, which is why
  Boost can afford g=20.32; the partial-fraction form is not.  Sweeping (g, N)
  under simulated DD arithmetic (106-bit) over the accuracy test's
  uniform(0.1, 50) input range gives an interior optimum near g=14, N=17.
  Run with --scan to reproduce that sweep.  The shipped configuration is
  g=14, N=17 (measured under the retired dd_accuracy_test: tgamma mean 28.30
  digits against a gate of 25.91; tgamma is now scored per point by the sweep).

DEFAULTS
  --g 14 --n 17  reproduces exactly the constants currently in dd_math.hpp.
"""

import argparse

from mpmath import mp, mpf, gamma, sqrt, pi, exp, power, fabs, log10, matrix, lu_solve

WORK_DPS = 150


def lanczos_coeffs(g, N):
    """Solve for the N partial-fraction coefficients at working precision."""
    mp.dps = WORK_DPS
    g = mpf(g)

    def Fg(z):
        t = z + g + mpf("0.5")
        return gamma(z + 1) / (sqrt(2 * pi) * power(t, z + mpf("0.5")) * exp(-t))

    A = matrix(N, N)
    b = matrix(N, 1)
    for r in range(N):
        z = mpf(r)
        b[r] = Fg(z)
        A[r, 0] = mpf(1)
        for k in range(1, N):
            A[r, k] = 1 / (z + k)
    return g, list(lu_solve(A, b))


def dd_split(c):
    """Split a high-precision value into a (hi, lo) double-double pair."""
    mp.dps = WORK_DPS
    hi = float(c)                    # nearest double
    lo = float(c - mpf(hi))          # remainder, rounded to the nearest double
    return hi, lo


def bits(x):
    import struct
    return struct.unpack("<Q", struct.pack("<d", x))[0]


def emit(g, N):
    g, a = lanczos_coeffs(g, N)
    print(f"    // Lanczos g={g} (exactly representable), N={N} partial-fraction terms.")
    print(f"    // Generated by scripts/gen_dd_lanczos_coeffs.py --g {g} --n {N}")
    for i, c in enumerate(a):
        hi, lo = dd_split(c)
        print(
            f"    const DoubleDouble c{i}  = DoubleDouble::from_bits("
            f"0x{bits(hi):016x}ULL, 0x{bits(lo):016x}ULL); // {mp.nstr(c, 34)}"
        )
    # sqrt(2*pi) leading factor
    mp.dps = WORK_DPS
    s2pi = sqrt(2 * pi)
    hi, lo = dd_split(s2pi)
    print(
        f"    const DoubleDouble sqrt_2pi = DoubleDouble::from_bits("
        f"0x{bits(hi):016x}ULL, 0x{bits(lo):016x}ULL); // {mp.nstr(s2pi, 34)}"
    )
    # verification block
    verify(g, a, N)


def verify(g, a, N):
    """Report accuracy under simulated DD (106-bit) arithmetic."""
    mp.dps = WORK_DPS
    samples = [mpf("0.5") + (mpf("49.5") * i) / mpf(99) for i in range(100)]
    digits = []
    for av in samples:
        mp.prec = 500
        true = gamma(av)
        mp.prec = 106                       # simulate DD working precision
        x = av - 1
        t = x + g + mpf("0.5")
        s = mpf(a[0])
        for k in range(1, N):
            s = s + mpf(a[k]) / (x + k)
        val = sqrt(2 * pi) * s * power(t, x + mpf("0.5")) * exp(-t)
        mp.prec = 500
        rel = fabs((val - true) / true)
        digits.append(-log10(rel) if rel > 0 else mpf(40))
    mp.dps = WORK_DPS
    mean = float(sum(digits) / len(digits))
    print(f"    // Simulated-DD accuracy over [0.5, 50]: mean {mean:.2f} digits, "
          f"min {float(min(digits)):.2f}, max|c_k| ~ 1e{float(log10(max(fabs(v) for v in a))):.1f}")


def scan():
    mp.dps = WORK_DPS
    samples = [mpf("0.5") + (mpf("49.5") * i) / mpf(99) for i in range(100)]
    print(" g      N     mean    min   log10|c|max")
    for g, N in [(7, 9), (10.9, 13), (12, 15), (13, 15), (14, 16), (14, 17),
                 (15, 17), (16, 18), (17, 19), (20.3209821879863739013671875, 24),
                 (22, 26)]:
        gg, a = lanczos_coeffs(g, N)
        digits = []
        for av in samples:
            mp.prec = 500
            true = gamma(av)
            mp.prec = 106
            x = av - 1
            t = x + gg + mpf("0.5")
            s = mpf(a[0])
            for k in range(1, N):
                s = s + mpf(a[k]) / (x + k)
            val = sqrt(2 * pi) * s * power(t, x + mpf("0.5")) * exp(-t)
            mp.prec = 500
            rel = fabs((val - true) / true)
            digits.append(-log10(rel) if rel > 0 else mpf(40))
        mp.dps = WORK_DPS
        print(f" {float(g):<6.4g} {N:<4} {float(sum(digits)/len(digits)):7.2f} "
              f"{float(min(digits)):6.2f}  {float(log10(max(fabs(v) for v in a))):6.1f}")


def emit_body(g, N):
    """Emit the complete unrolled tgamma series block for dd_math.hpp."""
    import struct
    g, a = lanczos_coeffs(g, N)
    gh = float(g + mpf("0.5"))
    L = []
    for i, c in enumerate(a):
        hi, lo = dd_split(c)
        L.append(f"    const DoubleDouble c{i:<2} = DoubleDouble::from_bits("
                 f"0x{bits(hi):016x}ULL, 0x{bits(lo):016x}ULL); // {mp.nstr(c, 32)}")
    mp.dps = WORK_DPS
    hi, lo = dd_split(sqrt(2 * pi))
    L.append(f"    const DoubleDouble sqrt_2pi = DoubleDouble::from_bits("
             f"0x{bits(hi):016x}ULL, 0x{bits(lo):016x}ULL); // sqrt(2*pi)")
    L.append("")
    L.append("    DoubleDouble x = subtract(a, DoubleDouble(1.0));")
    L.append(f"    DoubleDouble t = add(x, DoubleDouble({gh!r}));  // x + g + 1/2")
    L.append("    DoubleDouble s = c0;")
    for k in range(1, N):
        L.append(f"    s = add(s, divide(c{k}, add(x, DoubleDouble({float(k)!r}))));")
    print("\n".join(L))


if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("--g", type=float, default=14.0)
    p.add_argument("--n", type=int, default=17)
    p.add_argument("--scan", action="store_true")
    args = p.parse_args()
    if args.scan:
        scan()
    else:
        emit(args.g, args.n)
